### ISSUE TITLE
Compile failure with base-4.7

### ISSUE THREAD

**Issue by hvr** [mkdag/ast-monad#1]
The package declares to be compatible with `base >= 4.7 && < 5`, however with a pre-AMP base-4.7 we get a compile failure:

```
Configuring component lib from ast-monad-0.1.0.0...
Preprocessing library ast-monad-0.1.0.0...
[1 of 1] Compiling Language.ASTMonad ( src/Language/ASTMonad.hs, /tmp/matrix-worker/1493302032/dist-newstyle/build/x86_64-linux/ghc-7.8.4/ast-monad-0.1.0.0/build/Language/ASTMonad.o )

src/Language/ASTMonad.hs:38:10:
    Not in scope: type constructor or class ‘Applicative’
```

You can correct this yourself at https://hackage.haskell.org/package/ast-monad-0.1.0.0/ast-monad.cabal/edit

If you have any questions, please let me know!

**Comment by spica314** [comment]
Thank you. I corrected the dependencies.
